// Nathan Shulkin
// Lujo Lifestyle script
//
// All code was written and/or generated by Nathan Shulkin
// for use in the LUJO website and is therefore
// intellectual property of Nathan Shulkin; whom has given
// permission for LUJO to use code in accordance with
// agreed upon terms. Any attempt to use this code without
// permission from the author is prohibited.
//

const app = document.getElementById('root');

// create containers for main, hand bags, boots, story
const mainContainer = document.createElement('div');
mainContainer.setAttribute('class', 'container');

const photoCard = document.createElement('div');
photoCard.setAttribute('class', 'card');

const photo = document.createElement('img');
photo.src="Lujo_white_FINAL-02.png";
photoCard.appendChild(photo);

const text = document.createElement('p');
text.textContent="The Lujo website is currently being built, but it will be ready soon."
                  + " We appreaciate your patience."
text.style.margin="auto";

mainContainer.appendChild(photoCard);
mainContainer.appendChild(text);


app.appendChild(mainContainer);

